language: php

sudo: required

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: master

  allow_failures:
    - php: master

services:
  - mysql
  - redis-server
  - docker

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer config -g process-timeout 900 && composer update

script:
  - composer analyse
  - composer test
